# Generated by Django 5.2.7 on 2025-10-13 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Dni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=9, null=True)),
                ('nie', models.CharField(blank=True, max_length=9, null=True)),
                ('passport', models.CharField(blank=True, max_length=9, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.person')),
            ],
        ),
    ]
