# Generated by Django 5.2.7 on 2025-10-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dni',
            name='nie',
        ),
        migrations.RemoveField(
            model_name='dni',
            name='passport',
        ),
        migrations.AlterField(
            model_name='dni',
            name='dni',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dni',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.person'),
        ),
    ]
