# Generated by Django 5.2.7 on 2025-10-20 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_dni_nie_remove_dni_passport_alter_dni_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dni',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dnis', to='blog.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
