# Generated by Django 5.2.7 on 2025-10-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_dni_person_alter_person_name_alter_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dni',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.person'),
        ),
    ]
