# Generated by Django 5.2.7 on 2025-10-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='propic',
        ),
        migrations.AddField(
            model_name='person',
            name='propic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
