# Generated by Django 5.2.7 on 2025-12-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_is_player1_turn_game_player1_game_player2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='active_player',
        ),
    ]
